apiVersion: skaffold/v2beta20
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: krony
deploy:
  kubectl:
    manifests:
      - k8s/*
portForward:
  - resourceType: deployment
    resourceName: krony
    port: krony-http
    localPort: 9090
